
server:
  port: 8088
#spring.mvc.throw-exception-if-no-handler-found=true 
#spring.web.resources.add-mappings=false

#database configuration:sql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#set size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#spring.security.user.name=neeraj
#spring.security.user.password=neeraj
#spring.security.user.roles=ADMIN
project:
  image: images/

#spring security
#logging:
#  level:
#    org:
#      springframework:
#        security==DEBUG

springdoc:
  swagger-ui.path: /swagger-ui.html
secret:
  key: secret